export const LOADING = "LOADING";

export const FETCH_DATA_PENDING = "FETCH_USERS_PENDING";
export const FETCH_DATA_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_DATA_ERROR = "FETCH_USERS_ERROR";
